# Generated by Django 6.0.7 on 2026-08-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='budget',
            field=models.CharField(choices=[('Under $10,000', 'Under $10,000'), ('$10,000 - $30,000', '$10,000 - $30,000'), ('$30,000 - $75,000', '$30,000 - $75,000'), ('$75,000+', '$75,000+')], max_length=255),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='property_type',
            field=models.CharField(choices=[('Residential Villa / Home', 'Residential Villa / Home'), ('Commercial / Office Space', 'Commercial / Office Space'), ('Hospitality / Restaurant', 'Hospitality / Restaurant'), ('Retail Storefront', 'Retail Storefront')], max_length=255),
        ),
    ]
