# Generated by Django 6.0.7 on 2026-08-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_alter_consultation_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='preference',
            field=models.CharField(choices=[('In-Studio (Nairobi)', 'In-Studio (Nairobi)'), ('Virtual / Online', 'Virtual / Online')], max_length=255),
        ),
    ]
