# Generated by Django 6.0.7 on 2026-08-07 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial / Office'), ('hospitality', 'Hospitality & Restaurants'), ('retail', 'Retail & Showrooms')], max_length=50)),
                ('description', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(default='Nairobi, Kenya', max_length=150)),
                ('completion_year', models.IntegerField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='portfolio/covers/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='portfolio/before/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='portfolio/gallery')),
                ('caption', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.project')),
            ],
        ),
    ]
